# Generated by Django 5.2 on 2025-05-03 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['name', 'value'], name='api_product_name_b61153_idx'),
        ),
    ]
